spring:
    application:
        name: springboot-rabbitmq
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        #发布确认
        publisher-confirms: true
        virtual-host: /